### ISSUE TITLE
Grafana dashboard

### ISSUE THREAD

**Issue by callum-p** [brennerm/aws-quota-checker#10]
Hi there,

Good stuff, I've just deployed this in my environment.

Would you be able to please provide an export of your Grafana dashboard json?

**Comment by brennerm** [comment]
[Here](https://github.com/brennerm/aws-quota-checker/blob/master/grafana-dashboards/on-demand-ec2.json) you go. :+1:

**Comment by callum-p** [comment]
> [Here](https://github.com/brennerm/aws-quota-checker/blob/master/grafana-dashboards/on-demand-ec2.json) you go. +1

Nice, thanks
