### ISSUE TITLE
New Check - SES Sending Limits

### ISSUE THREAD

**Issue by camaya-caylent** [brennerm/aws-quota-checker#13]
- Sending Quota
- Quota Used
- Max Send Rate

That would be nice to have.

Thanks for this awesome tool.

**Comment by brennerm** [comment]
Thanks for reporting and your feedback.

Will see what I can do. :+1:

**Comment by brennerm** [comment]
@camaya-caylent The 24 hour sending quota is available in version [1.5.0](https://github.com/brennerm/aws-quota-checker/releases/tag/1.5.0).

Regarding the sending rate, AWS doesn't expose any information about the current rate so adding only the maximum doesn't make too much sense IMO. Hope you agree. :)
