### ISSUE TITLE
[New Check] Roles in an AWS account

### ISSUE THREAD

**Issue by charleshepner** [brennerm/aws-quota-checker#22]
The AWS console is warning us about getting close to the limit for number of IAM roles (1000).  Would like to have a check for this limit.

https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-quotas.html#reference_iam-quotas-entities

**Comment by brennerm** [comment]
Implemented in https://github.com/brennerm/aws-quota-checker/commit/da7b983f4ee9eefd84d4ecbd1da2b0bbe1b30452
