### ISSUE TITLE
SNS SMS quota

### ISSUE THREAD

**Issue by coderbec** [brennerm/aws-quota-checker#3]
I think I am correct in not seeing this in current checks.

Thanks

**Comment by brennerm** [comment]
Yup, you're right. Will take care of it. 👍

**Comment by brennerm** [comment]
@coderbec I added a few SNS checks with #4 but I wasn't able to implement the SMS spending limit check yet. Seems like there's a way to get the current amount [using Cloudwatch](https://docs.aws.amazon.com/pinpoint/latest/userguide/channels-sms-monitor-spending.html#channels-sms-monitor-spending-metrics) but as I don't use this feature CloudWatch doesn't return any value for my account.

Can you try to receive your current amount spent using the AWS CLI tool and post the resulting output?

**Comment by brennerm** [comment]
Closing due to no response. Feel free to reopen. :)
